# Generated by Django 2.1.2 on 2018-10-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmunm', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='reg_date',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
