# Generated by Django 2.1.2 on 2018-10-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmunm', '0003_auto_20181028_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
