# Generated by Django 2.1.2 on 2018-10-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmunm', '0004_auto_20181028_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='memo',
            field=models.CharField(max_length=500),
        ),
    ]
